name: MQTT Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: mqtt
    required: true
  - name: MQTT_CLIENT_ID
    inputType: FreeText
    description: A client ID for the sink
    defaultValue: mqtt-sink
    required: true
  - name: MQTT_TOPIC_ROOT
    inputType: FreeText
    multiline: false
    description: The root for messages in MQTT, this can be anything
  - name: MQTT_SERVER
    inputType: FreeText
    description: The address of your MQTT server
    required: true
  - name: MQTT_PORT
    inputType: FreeText
    description: The port of your MQTT server
    defaultValue: 8883
    required: true
  - name: MQTT_USERNAME
    inputType: FreeText
    description: The username to connect to MQTT with
    required: true
    value: admin
  - name: MQTT_PASSWORD
    inputType: Secret
    description: The password to connect to MQTT with
    required: true
    secretKey: MQTT_PASSWORD
  - name: MQTT_VERSION
    inputType: FreeText
    description: MQTT protocol version; choose 3.1, 3.1.1, or 5
    defaultValue: 3.1.1
    required: true
  - name: MQTT_USE_TLS
    inputType: FreeText
    description: Set to true if the server uses TLS
    defaultValue: "true"
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: mqtt_function.py
libraryItemId: mqtt-destination
